name: Build PDF Border Tool (Windows Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install PyQt5==5.15.10
        python -m pip install PyMuPDF==1.23.22
        python -m pip install Pillow==10.2.0
        python -m pip install opencv-python==4.9.0.80
        python -m pip install numpy==1.24.4
        python -m pip install pyinstaller==6.3.0
    
    - name: Verify installations
      run: |
        python -c "import PyQt5; print('✅ PyQt5 OK')"
        python -c "import fitz; print('✅ PyMuPDF OK')"
        python -c "import PIL; print('✅ Pillow OK')"
        python -c "import cv2; print('✅ OpenCV OK')"
        python -c "import numpy; print('✅ NumPy OK')"
        python -m PyInstaller --version
    
    - name: Build Windows executable
      run: |
        python -m PyInstaller --onefile --windowed --name=PDFBorderTool --hidden-import=PyQt5.sip --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtGui --collect-all=cv2 main.py
    
    - name: Verify executable was created
      run: |
        dir dist
        echo "File size:"
        powershell -command "(Get-Item dist\PDFBorderTool.exe).length"
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: PDFBorderTool-Windows
        path: dist/PDFBorderTool.exe
        retention-days: 30
